output:
  directory: output

data:
  raw_directory: data/raw
  interim_directory: data/interim
  processed_directory: data/processed
  external_directory: data/external

notebooks:
  directory: source/notebooks
